DROP DATABASE IF EXISTS demo_blog;
CREATE DATABASE demo_blog;

SELECT * FROM demo_blog.Posts;

INSERT INTO demo_blog.Categories (name) VALUES ("Tech Tips"), ("Personal"), ("Deep Thoughts");
INSERT INTO demo_blog.Posts (title, text, CategoryId) VALUES 
("Sequelize Associations" 
, "You can group more than one association inside your .associate block! Business-to-consumer ownership equity beta stealth holy grail niche market technology agile development iPhone direct mailing pitch. Pivot gen-z value proposition conversion termsheet advisor pitch lean startup supply chain stock first mover advantage scrum project backing. Technology infrastructure founders investor disruptive return on investment business plan graphical user interface conversion prototype analytics network effects deployment strategy. Funding first mover advantage growth hacking alpha. Handshake validation facebook seed round churn rate focus mass market growth hacking social proof lean startup partnership leverage. Ecosystem partnership creative leverage user experience A/B testing channels business-to-consumer android. Seed round business-to-consumer freemium iPad iPhone interaction design conversion long tail incubator business plan value proposition. Churn rate beta product management startup long tail iteration seed money ecosystem graphical user interface hypotheses user experience crowdsource termsheet. Ownership learning curve A/B testing value proposition partner network funding focus startup. Accelerator social proof facebook iteration termsheet disruptive monetization.

Beta holy grail vesting period product management iPad niche market deployment pivot crowdsource leverage channels. Seed round branding lean startup paradigm shift equity research & development infographic agile development mass market user experience churn rate launch party bandwidth. Pitch interaction design bandwidth value proposition angel investor facebook direct mailing niche market branding business plan pivot infographic iPhone. First mover advantage angel investor research & development virality focus vesting period. Network effects conversion startup validation. Strategy leverage paradigm shift accelerator crowdfunding alpha. Strategy beta low hanging fruit interaction design prototype crowdsource release disruptive iPad seed round handshake angel investor android channels. Direct mailing social proof beta stock paradigm shift virality leverage buzz infrastructure startup. Responsive web design vesting period founders series A financing. IPhone seed money equity technology mass market backing advisor client branding.

Release ownership launch party conversion burn rate venture business-to-business responsive web design monetization MVP marketing. Churn rate beta leverage assets learning curve bandwidth channels analytics iPad return on investment series A financing growth hacking. Mass market prototype entrepreneur branding crowdsource twitter creative. Ownership gen-z social proof niche market gamification early adopters rockstar crowdsource metrics hypotheses. Gamification seed round branding traction deployment advisor customer beta channels user experience funding sales twitter buzz. Buzz stock early adopters facebook client research & development paradigm shift return on investment monetization infrastructure. Mass market venture technology facebook branding. Supply chain market disruptive gen-z graphical user interface android ownership angel investor pitch infrastructure. Incubator validation twitter long tail analytics. Conversion responsive web design direct mailing seed round innovator hackathon assets handshake validation network effects equity."
, 1),
("Sequelize + React"
, "When using a Node/Express/Sequelize back-end with a React front-end, your React app will make Ajax calls to the back-end routes to interact with your database. Any non-data routing should be handled via React Router!

Hackathon funding equity advisor growth hacking analytics angel investor business-to-consumer seed money graphical user interface traction buyer. Handshake product management research & development graphical user interface crowdfunding twitter buzz technology churn rate sales. Channels product management direct mailing scrum project launch party agile development holy grail sales first mover advantage accelerator technology user experience. Lean startup technology MVP first mover advantage entrepreneur startup infographic. Analytics burn rate prototype client validation deployment return on investment hackathon alpha monetization handshake. Crowdsource analytics deployment bootstrapping. Series A financing long tail social media leverage advisor partnership scrum project ownership equity gen-z stealth analytics iPad user experience. Assets metrics holy grail strategy. Hackathon disruptive buyer leverage research & development channels social media buzz. Analytics early adopters long tail business-to-business venture termsheet market lean startup business plan seed money virality stock.

Startup mass market angel investor gen-z business-to-business metrics partner network research & development graphical user interface buyer termsheet backing. Equity social media bandwidth niche market seed money early adopters analytics assets ownership. Equity holy grail low hanging fruit. Business-to-business network effects creative rockstar pivot release accelerator. Buzz stealth churn rate graphical user interface rockstar series A financing bandwidth business-to-consumer accelerator user experience crowdfunding. Alpha social media supply chain venture focus entrepreneur seed round analytics customer validation creative strategy gamification. Android non-disclosure agreement rockstar seed money early adopters freemium iPad A/B testing business-to-business equity pitch leverage infographic. "
, 1),
("An Ode to Cheeseburgers"
, "Think of cheeseburgers like a Tinder match. They might not all be your soulmate but you’ve gotta find out to be sure. It can get a little messy and that’s just part of the fun.

Some are cheesy, others can be a little dry, and the rare few are a disaster. There are so many cheeseburgers out there it can be hard to commit to just one favourite. That being said, when you know, you just know.

Everyone has their perfect match. Sometimes it’s just around the corner, other times you have to travel the world in search of it. Wherever your perfect cheeseburger is, it’s out there."
, 3),
("From Pirate to Web Developer: A Study",
"Coxswain long boat Cat o'nine tails knave prow piracy scuppers snow aft lateen sail strike colors. Hogshead reef sails jury mast Jack Ketch chandler squiffy square-rigged black jack bilge water deadlights yo-ho-ho. Scourge of the seven seas lateen sail black spot capstan hulk parrel case shot pink gangplank list tackle. Carouser measured fer yer chains lateen sail chandler Davy Jones' Locker bilge aye clipper list Pieces of Eight crow's nest.

Mizzen brig jolly boat nipperkin Sink me tack to go on account deadlights yo-ho-ho gangway brigantine. Landlubber or just lubber Yellow Jack brigantine gabion bring a spring upon her cable case shot Chain Shot Sail ho Privateer scallywag cable. Grog reef sails pirate gaff lookout bilge rat boom barque gun haul wind Blimey. Admiral of the Black Arr bilge rat aft lad keelhaul Brethren of the Coast nipperkin chandler haul wind long clothes.

Bilge wench furl doubloon starboard ahoy lad Pieces of Eight broadside hornswaggle heave to. Salmagundi hempen halter list port nipperkin splice the main brace mizzenmast killick gaff keel yardarm. Hands ballast starboard to go on account tackle brig dead men tell no tales broadside ye pressgang rope's end. Main sheet crack Jennys tea cup maroon poop deck run a rig handsomely piracy Jolly Roger prow Plate Fleet grog blossom.

Spanish Main lee chase guns chantey Admiral of the Black bounty six pounders pinnace Nelsons folly nipper Jack Tar. Admiral of the Black bucko main sheet jib chase guns pink Davy Jones' Locker maroon jack cackle fruit lass. Gun scallywag take a caulk overhaul Jack Tar chase dead men tell no tales Buccaneer ballast prow measured fer yer chains. Mutiny yawl stern matey provost Sail ho tackle quarterdeck gunwalls draft pirate.

Yo-ho-ho gun clap of thunder lugsail deadlights trysail main sheet hail-shot aft sheet matey. Long boat grog blossom shrouds fluke sloop cackle fruit gaff come about lookout rutters smartly. Parrel bowsprit Arr yardarm Jack Tar line warp me sutler man-of-war careen. Cackle fruit poop deck league rope's end gunwalls yard barkadeer skysail take a caulk hardtack sutler.)"
, 2);
